#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias grep="grep --ignore-case --color"
alias javarun="~/.bin/java.sh"
alias usaco="~/.bin/usaco.sh"
alias shutdown="kill $(pgrep spotify) && reboot)"
alias reboot="kill $(pgrep spotify) && reboot)"
