let mapleader=" "

set number
set relativenumber
set ruler
syntax enable
set showcmd
set cursorline
set showmatch
set incsearch
set hlsearch
set mouse=a
:imap kj <Esc>

function! NumberToggle()
  if(&relativenumber == 1 && &number == 1)
    set number
    set norelativenumber
  elseif (&number == 1 && &relativenumber == 0)
    set norelativenumber
    set nonumber
  else
    set number
    set relativenumber
  endif
endfunc

" toggle line numbers
nnoremap <leader>l :call NumberToggle()<CR>
" join lines without moving cursor
nnoremap J mzJ`z
" center easily 
nnoremap <leader><Space> zz

nnoremap XX ZQ

set clipboard^=unnamedplus,unnamed

" Make Y move like D and C
noremap Y y$

command W w !sudo tee "%" > /dev/null

" turn on undo files, put them in a common location
set undofile
set undodir=~/.vim/_undo/
