config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_config:
    dst: ~/.config
    src: .config
  d_scripts:
    dst: ~/.scripts
    src: scripts
  f_bashrc:
    dst: ~/.bashrc
    src: .bashrc
  f_gdbinit:
    dst: ~/.gdbinit
    src: .gdbinit
  f_grub:
    dst: /etc/default/grub
    src: .etc/default/grub
  f_hosts:
    dst: /etc/hosts
    src: .etc/hosts
  f_inputrc:
    dst: ~/.inputrc
    src: .inputrc
  f_nanorc:
    dst: ~/.nanorc
    src: .nanorc
  f_prefs:
    dst: ~/.config/spotify/Users/liu.benjamin-user/prefs
    src: .config/spotify/Users/liu.benjamin-user/prefs
  f_userchrome.css:
    dst: ~/.mozilla/firefox/hun1lqus.default/chrome/userChrome.css
    src: .mozilla/firefox/hun1lqus.default/chrome/userChrome.css
  f_vimrc:
    dst: ~/.vimrc
    src: .vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: .xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: .Xresources
profiles:
  arch:
    dotfiles:
    - d_config
    - f_userchrome.css
    - f_grub
    - f_hosts
    - f_xresources
    - f_nanorc
    - f_xinitrc
    - f_bashrc
    - f_vimrc
    - f_prefs
    - f_gdbinit
    - f_inputrc
    - d_scripts
