config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_bin:
    dst: ~/.bin
    src: bin
  d_config:
    dst: ~/.config
    src: config
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_greenclip.cfg:
    dst: ~/.config/greenclip.cfg
    src: config/greenclip.cfg
  f_grub:
    dst: /etc/default/grub
    src: etc/default/grub
  f_i3_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_nanorc:
    dst: ~/.nanorc
    src: nanorc
  f_treestyletab.css:
    dst: ~/.config/treestyletab.css
    src: config/treestyletab.css
  f_userchrome.css:
    dst: ~/.mozilla/firefox/hun1lqus.default/chrome/userChrome.css
    src: mozilla/firefox/hun1lqus.default/chrome/userChrome.css
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  arch:
    dotfiles:
    - d_config
    - f_xresources
    - f_userchrome.css
    - d_bin
    - f_nanorc
    - f_xinitrc
    - f_gitconfig
    - f_greenclip.cfg
    - f_i3_config
    - f_bashrc
    - f_treestyletab.css
    - f_grub
