config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_config:
    dst: ~/.config
    src: config
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_grub:
    dst: /etc/default/grub
    src: etc/default/grub
  f_hosts:
    dst: /etc/hosts
    src: etc/hosts
  f_nanorc:
    dst: ~/.nanorc
    src: nanorc
  f_userchrome.css:
    dst: ~/.mozilla/firefox/hun1lqus.default/chrome/userChrome.css
    src: mozilla/firefox/hun1lqus.default/chrome/userChrome.css
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  arch:
    dotfiles:
    - d_config
    - f_userchrome.css
    - f_grub
    - f_hosts
    - f_xresources
    - f_nanorc
    - f_xinitrc
    - f_bashrc
    - f_vimrc
