#!/bin/bash
#
# http://github.com/mitchweaver/bin
#
# Records a selected rectangle with ffmpeg.
#

set $(slop -q -o -f '%x %y %w %h')

ffmpeg -y -f x11grab -s ${3}x${4} \
    -r 75 -i :0.0+${1},${2} -qscale 0 \
    "record $(date '+%m-%d-%y%l:%M %p')".webm \
    > /dev/null 2>&1
